### ISSUE TITLE
Series tooltip doesn't work in Safari

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-charts#526]
- Open https://charts.demo.vaadin.com/PieWithLegend in Safari
- Hover over any series point

### Expected
- Series tooltip is shown
![expected](https://user-images.githubusercontent.com/262432/47015244-24863280-d155-11e8-976e-abfac5a06648.png)

### Actual
- No tooltip
![actual](https://user-images.githubusercontent.com/262432/47015267-2ea83100-d155-11e8-9d96-f31d9aa81f57.png)

### Notes
- It works with Chrome and Firefox. Tested with Safari 12. 
- The WC demo works in Safari
- There seems to be one issue with the filter which adds a shadow in the tooltip box that is preventing the tooltip to display correctly and only affects Charts for Flow component.

**Comment by web-padawan** [comment]
Tested the [demo](https://demo.vaadin.com/charts/PieWithLegend) in Safari 14 and it works.

![demo](https://user-images.githubusercontent.com/10589913/100740732-d8a0b100-33e1-11eb-9686-12e9444635f2.png)

The demo is still using `vaadin-charts` 6.2.2 so I assume the underlying bug was fixed in Safari. Closing.
