### ISSUE TITLE
Dynamically styling Vaadin Charts 6

### ISSUE THREAD

**Issue by BL-AMC** [vaadin/vaadin-charts#531]
I am trying to style Charts dynamically. This includes styling a series as a whole but also single items, plotlines and plotbands.

Sadly this is not so easy in Vaadin 10 as many methods for styling, like setColor(), setDashStyle() and many others, have been removed.
My current approach to this is to add a classname to every element i need to style and adding the required CSS styles to a `<style>`. This is then added as a sibling to the chart like this:
	
![](https://i.imgur.com/jR9GQS2.png)

This currently works in Firefox since they don't support Shadow-DOM *yet*. This will change when they release Firefox v63 on 23rd of October this year.

This **doesn't** work in browsers which support Shadow-DOM e.g. Chrome. My current solution for browsers supporting Shadow-DOM is to move the aforementioned `<style>` via javascript into the Light-DOM of the Vaadin-Chart which would look like this:

![](https://i.imgur.com/3bcIUKF.png)

This is the command used to do this:

```java
UI.getCurrent().getPage().executeJavaScript("document.getElementById(\"" + the-chart-id-goes-here + "\").getElementsByTagName(\"vaadin-chart\")[0].shadowRoot.appendChild(document.getElementById(\"" + the-style-id-goes-here + "\"))" );
```

I made a little [demo](https://github.com/BL-AMC/Vaadin-Charts-dynamic-styling) showcasing a stripped down version of my current solution.
To run, just clone the project and run `mvn jetty:run`

Although it works it isn't an elegant solution. A better word might be ugly.

Is there any different way to style Vaadin-Charts dynamically? (using a mixin which exposes all my stylable items to CSS-variables is not sufficient as it would not allow me to style single items.)

**Comment by rolfsmeds** [comment]
Documentation for how to style charts with css can be found here: https://vaadin.com/docs/v14/charts/java-api/css-styling.html

You can make the colors applied that way more dynamic by using css variables instead of hardcoded color values, e.g.
`fill: var(--some-dynamic-color);`
Then you can set the value of that variable dynamically from java code:
`chart.getStyle().set("--some-dynamic-color", "#aa7739");`

But, as mentioned above, Vaadin Charts 9.0 also brings back Java styling mode https://github.com/vaadin/vaadin-charts-flow/releases/tag/9.0.0
This is currently available for V18, but will be made available for V14.5 (although you'll probably need to bump your charts version separately, as it will not be released as a part of the V14.5 platform).
